var consts;
consts = (typeof exports != "undefined") ? exports : window;
consts.AUTH = 'auth';
consts.BROADCAST = 'brmsg';
consts.UNICAST = 'unmsg';
consts.ADDU = 'adduser';
consts.REMOVEU = 'remuser';
consts.RETRIEVE = 'retrieve';
consts.BR_IMG = 'brimg';
consts.UNI_IMG = 'uniimg';
